/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-echarts/src/BarEchart.vue')['default']
    BaseEchart: typeof import('./src/components/page-echarts/src/BaseEchart.vue')['default']
    BreadCrumb: typeof import('./src/components/main-header/cpns/BreadCrumb.vue')['default']
    LineEchart: typeof import('./src/components/page-echarts/src/LineEchart.vue')['default']
    MainHeader: typeof import('./src/components/main-header/MainHeader.vue')['default']
    MainMenu: typeof import('./src/components/main-menu/MainMenu.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/MapEchart.vue')['default']
    PageContent: typeof import('./src/components/page-content/PageContent.vue')['default']
    PageModal: typeof import('./src/components/page-modal/PageModal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/PageSearch.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/PieEchart.vue')['default']
    RoseEchart: typeof import('./src/components/page-echarts/src/RoseEchart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserState: typeof import('./src/components/main-header/cpns/UserState.vue')['default']
  }
}
